"""Add freebie-dev and freebie-company relationship

Revision ID: 26667fa5e020
Revises: 0f30f97c007e
Create Date: 2024-09-12 19:47:05.521572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26667fa5e020'
down_revision = '0f30f97c007e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
