"""Add a freebie method print_details

Revision ID: b9f0442ffcfb
Revises: c154047a040a
Create Date: 2024-09-12 21:59:25.878579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f0442ffcfb'
down_revision = 'c154047a040a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
