"""Edit company_dev Association Table

Revision ID: c154047a040a
Revises: 409ea26af3c9
Create Date: 2024-09-12 20:39:25.618148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c154047a040a'
down_revision = '409ea26af3c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
