"""Add methods

Revision ID: ddd60f7f799d
Revises: b9f0442ffcfb
Create Date: 2024-09-12 23:25:28.568489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd60f7f799d'
down_revision = 'b9f0442ffcfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
